package:
  name: kippenhahn
  version: "v0.0.4"

source:
  git_rev: v0.0.4
  git_url: https://github.com/POSYDON-code/kippenhahn.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - astropy
    - multiprocess
    - matplotlib

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - astropy
    - multiprocess
    - matplotlib

test:
  imports: kippenhahn

about:
  home: https://github.com/POSYDON-code/kippenhahn